name: Branch Protection

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the push is direct
        run: |
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
            echo "Direct push to main branch detected. This is not allowed."
            echo "Please create a pull request to merge changes into main."
            exit 1
          fi